### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Mearafat** [initstring/cloud_enum#17]
Getting error while running,
python cloud_enum.py -k xxx
[!] Cannot access mutations file: /enum_tools/fuzz.txt

**Comment by initstring** [comment]
Hi @Mearafat 

This seems identical to the previous issue you opened here: https://github.com/initstring/cloud_enum/issues/15

Has something changed? Can you try running the tool again like this:

`./cloud_enum.py -k xxx`

I can't seem to replicate your error with the newest version of cloud_enum, as well (fixed it the last time you opened the issue). Are you running the latest version?

Thanks!

**Comment by Mearafat** [comment]
Hi,

It's fixed now. Thanks!

**Comment by initstring** [comment]
Great, thanks!
