### ISSUE TITLE
requirements.txt invocation to be change in readme.md

### ISSUE THREAD

**Issue by ipentest** [initstring/cloud_enum#20]
Hi,

Currently in the setup part of readme.md, the method to install from requirements.txt is given as follows:

pip3 install -r ./requirements.txt

This should be changed to

pip3 install -r requirements.txt

Thanks for the awesome work,
Kiran

**Comment by initstring** [comment]
Hi,
Thanks for taking the time to open an issue!
`./` specifies the current working directory to be the path of the requirements.txt file. Why should this be changed?
I believe it should generally work either way, but including the path directive is more specific.

**Comment by initstring** [comment]
Closing.
