### ISSUE TITLE
error typo on open function

### ISSUE THREAD

**Issue by beachf2lightning** [initstring/cloud_enum#31]
The following is what it output before and after the crash...

root@csi-analyst:/home/csi/cloud_enum# python cloud_enum.py -k binance

##########################
        cloud_enum
   github.com/initstring
##########################

Keywords:    binance
Mutations:   /home/csi/cloud_enum/enum_tools/fuzz.txt
Brute-list:  /home/csi/cloud_enum/enum_tools/fuzz.txt

Traceback (most recent call last):
  File "cloud_enum.py", line 234, in <module>
    main()
  File "cloud_enum.py", line 213, in main
    mutations = read_mutations(args.mutations)
  File "cloud_enum.py", line 152, in read_mutations
    with open(mutations_file, encoding="utf8", errors="ignore") as infile:
TypeError: 'errors' is an invalid keyword argument for this function
root@csi-analyst:/home/csi/cloud_enum# python cloud_enum.py -k binance -ns binance.com

##########################

**Comment by initstring** [comment]
Thanks for taking the time to open an issue!

It looks like you might be using python2. You can try this instead:

```python3 cloud_enum.py -k binance```

And that should work.

Thanks!

**Comment by initstring** [comment]
And good luck with the Binance bug bounty!!! :D
