### ISSUE TITLE
Required permissions and address

### ISSUE THREAD

**Issue by cgaudit** [initstring/cloud_enum#39]
Hi
I would like to use the too but I have some questions which I could not resolve from the git description:
1. What permissions is required to run the too against each platform (AWS, Azure, GCP)?
2. Against which address I will use it in each of the platforms?
ASAP
Thank's ahead.

**Comment by initstring** [comment]
Hello. :)

There are no permissions required to run this tool, and there is no address you need to point it at. It's a reconnaissance tool meant to be used emulate an outsider's perspective.

You can follow the instructions here: https://github.com/initstring/cloud_enum#running
