### ISSUE TITLE
awsapps error. is this supposed to be happening?

### ISSUE THREAD

**Issue by ovladuk** [initstring/cloud_enum#43]
[!] DNS Timeout on content.REMOVED.awsapps.com. Investigate if there are many of these.    [!] DNS Timeout on REMOVED.awsapps.com. Investigate if there are many of these.

**Comment by initstring** [comment]
Hi @ovladuk - thanks for opening an issue!

I think that DNS timeouts would be more of host/network issue.

Do you get this for only awsapps checks, or others as well?

**Comment by initstring** [comment]
No reply, closing issue. Let me know if you are still having problems. Good luck!
