### ISSUE TITLE
firebaseio HTTPSConnectionPool  port=443): Pool is closed

### ISSUE THREAD

**Issue by unnimona** [initstring/cloud_enum#55]
Checking for Google Firebase Realtime Databases
    [!] Connection error on apple-6.firebaseio.com/.json:
HTTPSConnectionPool(host='apple-6.firebaseio.com', port=443): Pool is closed.
    [!] Connection error on apple7.firebaseio.com/.json:
HTTPSConnectionPool(host='apple7.firebaseio.com', port=443): Pool is closed.
    [!] Connection error on 8-apple.firebaseio.com/.json:
HTTPSConnectionPool(host='8-apple.firebaseio.com', port=443): Pool is closed.
  [1m[92mOPEN GOOGLE FIREBASE RTDB: https://apple1.firebaseio.com/.json[0m
  [1m[33mProtected Google Firebase RTDB: https://apple-2020.firebaseio.com/.json[0m
  [1m[33mProtected Google Firebase RTDB: https://apple-5.firebaseio.com/.json[0m
  [1m[33mProtected Google Firebase RTDB: https://apple-7.firebaseio.com/.json[0m
    100/961 complete...
    [!] Connection error on applebetas.firebaseio.com/.json:
HTTPSConnectionPool(host='applebetas.firebaseio.com', port=443): Pool is closed.
  [1m[31mThe Firebase database has been deactivated.: https://apple-betas.firebaseio.com/.json[0m
    200/961 complete...
    [!] Connection error on applecontent.firebaseio.com/.json:
HTTPSConnectionPool(host='applecontent.firebaseio.com', port=443): Pool is closed.
    [!] Connection error on core-apple.firebaseio.com/.json:
HTTPSConnectionPool(host='core-apple.firebaseio.com', port=443): Pool is closed.
  [1m[33mProtected Google Firebase RTDB: https://apple-container.firebaseio.com/.json[0m
  [1m[31mThe Firebase database has been deactivated.: https://apple-core.firebaseio.com/.json[0m
    300/961 complete...
  [1m[31mThe Firebase database has been deactivated.: https://dev-apple.firebaseio.com/.json[0m
  [1m[31mThe Firebase database has been deactivated.: https://apple-developer.firebaseio.com/.json[0m
  [1m[31mThe Firebase database has been deactivated.: https://apple-devops.firebaseio.com/.json[0m
  [1m[33mProtected Google Firebase RTDB: https://apple-downloads.firebaseio.com/.json[0m

how to fix?

**Comment by initstring** [comment]
Looks like a problem with your Internet connection. You can try running the tool with less concurrent threads, or try a more stable connection.

I'll close this issue, there is nothing here for me to troubleshoot.

If others come across this and are encountering this issue, we can re-open. But it just looks like network connectivity/stability to me.

Thanks and good luck!
