### ISSUE TITLE
Called from another script

### ISSUE THREAD

**Issue by timlaw71** [initstring/cloud_enum#56]
When I execute cloud_enum from inside another script it sometimes won't exit out of the script. I just see the "All done, happy hacking!" message and I have to ctrl-c out of the script.

**Comment by initstring** [comment]
Hi @timlaw71 - thanks for opening an issue!

Could you provide a bit more details, to see if I can reproduce? Maybe:

- What OS and shell you are using
- An example script that reproduces the issue
- Does it happen every time with that script, or just sometimes?

Thanks!

**Comment by timlaw71** [comment]
Linux kali 6.0.0-kali3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.7-1kali1 (2022-11-07) x86_64 GNU/Linux
I have run it from Bash and also directly from the terminal in Visual Studio Code.
It  doesn't happen everytime, but I'm using this command in my python script 
os.system("python3  cloud_enum.py -k " + sys.argv[2] + " -l ~/Documents/" + sys.argv[1] + "/output_files/cloud_enum_" + sys.argv[1] + ".csv -f csv")

**Comment by initstring** [comment]
If you reach the point where it says "happy hacking", you'll also get a `sys.exit()` which cleanly exits this script.

You can see this in the code [here](https://github.com/initstring/cloud_enum/blob/master/cloud_enum.py#L251).

It seems cloud_enum is working normally in this case, and I'm not sure why you're having issues with your script.

I would recommend against using `os.system` in general, though. You should be using [subprocess](https://docs.python.org/3/library/subprocess.html) instead.

I'm going to close this as it doesn't appear to be a cloud_enum issue. Feel free to re-open if you migrate to subprocess and can identify something specific in cloud_enum that is causing issues.

Thanks and good luck!

**Comment by timlaw71** [comment]
I tried subprocess and had the same issue.

**Comment by initstring** [comment]
Are you doing something with the output of cloud_enum? You didn't share your actual script, so it is hard for me to understand what you are doing. It's possible you're filling some buffer or waiting for something, I just don't know.

You can try using `strace` to see if it is stuck on some system calls, or some other interactive Python debugging process. But again, cloud_enum seems to make it to completion so I can't really troubleshoot as there are no errors, etc.
