### ISSUE TITLE
Unnecessary returning of variable or May be just forgot to do some logic ? 

### ISSUE THREAD

**Issue by grpnpraveen** [initstring/cloud_enum#58]
In the enum_tools dir , check the python file azure_checks.py. In this file, 
`  utils.fast_dns_lookup(candidates, nameserver,
                          callback=print_website_response,
                          threads=threads)`
These lines do nothing after getting a variable valid_names from fast_dns_lookup.
is it needed for some processing or just an accidental return ?

**Comment by initstring** [comment]
Hi @grpnpraveen - can you please provide the line number inside `azure_checks.py` that you are referring to?

Thanks!

**Comment by initstring** [comment]
Haven't heard back, closing issue.
