### ISSUE TITLE
Functionalities to parse and download file contents

### ISSUE THREAD

**Issue by Sambal0x** [initstring/cloud_enum#9]
Your tool has been awesome! Thanks for your hard work. 
Just a thought about adding an extra functionality to download the file content for an open storage/bucket would be pretty cool as well.

**Comment by initstring** [comment]
Great suggestion! I had a quick chat w/ @Sambal0x and determined that actually downloading everything automatically may cause a few issues. Instead, I implemented a new feature - the tool will output the full URL for each object inside the open buckets it finds. This makes it quick and easy to download manually or input into another tool.

Thanks mate!
